Esas/provide slider component 10462
Cosmo-Tech/webapp-component-ui pull request #286
Opened 2023-01-10 15:21 UTC by esasova

2023-01-16 16:13 UTC, csm-thu requested changes

2023-01-16 16:13 UTC, csm-thu commented on src/inputs/BasicInputs/BasicSliderInput/BasicSliderInput.js
> +          style={sliderProps}
`sliderProps` sounds too generic for the "style" prop of the Slider, maybe we could rename this prop to `sliderStyle` ?

2023-01-16 16:13 UTC, csm-thu commented on src/inputs/BasicInputs/BasicSliderInput/BasicSliderInput.js
> +          aria-labelledby="basic-slider-input-label"
`aria-labelledby` value should be "_The id of the element containing a label for the slider_", but the label associated to the slider is defined by `BasicInputWrapper`. If we don't force the `id` of the label in `BasicInputWrapper`, we should probably not define `aria-labelledby` here.

2023-01-17 14:48 UTC, nborde-CSM approved these changes
LGTM :+1:

2023-01-17 14:56 UTC, ardvi approved these changes
LGTM

2023-01-17 15:32 UTC, csm-thu approved these changes
LGTM :+1:

2023-01-18 14:49 UTC, merged