Nbo/migrate to m UI 5 prod 8916
Cosmo-Tech/webapp-component-ui pull request #305
Opened 2023-02-09 16:25 UTC by nborde-CSM

2023-02-10 15:32 UTC, csm-thu commented on src/buttons/CreateScenarioButton/components/CreateScenarioDialog/CreateScenarioDialog.js
> +import Autocomplete from '@mui/material/Autocomplete';
Can we merge this import with the import of `@mui/material` above ?

2023-02-10 15:52 UTC, csm-thu commented on src/cards/ScenarioNode/components/ConfirmDeleteDialog/ConfirmDeleteDialog.js
>          {/* TODO Use color="error" when MUI v5.x is used */}
`TODO` comment can be removed now :slightly_smiling_face:

2023-02-10 16:30 UTC, csm-thu commented on src/inputs/BasicInputs/BasicDateInput/BasicDateInput.js
> +import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';
These changes seem to cause warnings during the `yarn build` command:
```
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
@mui/x-date-pickers/AdapterDateFns (imported by "src/inputs/BasicInputs/BasicDateInput/BasicDateInput.js")
@mui/x-date-pickers/DesktopDatePicker (imported by "src/inputs/BasicInputs/BasicDateInput/BasicDateInput.js")
@mui/x-date-pickers//LocalizationProvider (imported by "src/inputs/BasicInputs/BasicDateInput/BasicDateInput.js")
```

Also, the `date-fns` dependency seems to be no longer used, could you remove it with `yarn remove date-fns` please ?

2023-02-10 17:34 UTC, csm-thu commented on src/inputs/BasicInputs/BasicInputWrapper/BasicInputWrapper.js
> +            <InfoOutlinedIcon className={classes.iconTooltip} fontSize="inherit" />
Is `iconTooltipStyle` no longer used ? We should probably remove the prop then.

2023-02-10 17:39 UTC, csm-thu requested changes
Some changes suggested

2023-02-13 13:27 UTC, esasova commented on src/misc/ScenarioValidationStatusChip/ScenarioValidationStatusChip.js
>    /// USE ERROR AND SUCCESS IN CHIP COLOR WHEN UPDATE TO MUI 5.X IS DONE
We still are using `background-color` property instead of `color` prop of mui5 `chip`

2023-02-13 14:12 UTC, nborde-CSM commented on doc/src/buttons/SignInButton.mdx
> +import withStyles from '@mui/styles/withStyles';
probably an old forgotten one

2023-02-13 14:16 UTC, nborde-CSM commented on src/charts/CytoViz/CytoViz.js
> +import { Autocomplete } from '@mui/lab';
Probably a mess during the Search/replace components migration

2023-02-17 10:06 UTC, csm-thu approved these changes
LGTM :+1:

2023-02-17 14:34 UTC, esasova approved these changes

2023-02-20 09:43 UTC, merged