THU/scenario_manager_tree_list_prod_7333
Cosmo-Tech/webapp-component-ui pull request #40
Opened 2021-07-26 15:25 UTC by csm-thu

2021-07-27 14:50 UTC, jreynard-code requested changes
Minor changes, LGTM ;)

2021-07-27 14:50 UTC, jreynard-code commented on src/ScenarioManagerTreeList/ScenarioManagerTreeList.js
> +function getScenariosCount (treeData) {
Can be moved into the core package ;)

2021-07-27 14:50 UTC, jreynard-code commented on src/ScenarioManagerTreeList/ScenarioManagerTreeList.js
> +  const [treeData, setTreeData] = useState(formatScenariosToRSTList(datasets, scenarios));
Could be interesting to use "useMemo" hooks here:

`const rstList = useMemo(() => formatScenariosToRSTList(datasets, scenarios), [datasets,scenarios]);
const [treeData, setTreeData] = useState(rstList); `

and in `filterScenarios` function

`  if (!searchStr || searchStr.length === 0) {
      setTreeData(rstList);
      return;
    }`

2021-07-27 14:50 UTC, jreynard-code commented on src/ScenarioManagerTreeList/components/ScenarioNode/ScenarioNode.js
> +function getDatasetNames (datasets, scenarioDatasets) {
Can be moved into the core package ;)

2021-07-28 06:28 UTC, merged

2021-07-28 06:46 UTC, csm-thu commented
@jreynard-code suggested changes have been done, thanks for the feedback ! :+1: