feat: implement help menu
Cosmo-Tech/webapp-component-ui pull request #78
Opened 2021-10-20 07:37 UTC by nborde-CSM

2021-10-20 08:54 UTC, COSMO-VMI requested changes
Just some setters and getters to rename, LGTM.

2021-10-20 08:54 UTC, COSMO-VMI commented on src/menus/UserInfo/UserInfo.js
> +    setLangIsMenuOpened(false);
Please name them `isLanguageMenuOpen` and `setLanguageMenuOpen` instead.

2021-10-20 08:54 UTC, COSMO-VMI commented on src/menus/HelpMenu/HelpMenu.js
> +  const [isMenuOpened, setIsMenuOpened] = useState(false);
Please name them `isMenuOpen` and `setMenuOpen` instead.

2021-10-21 08:00 UTC, jreynard-code commented on src/menus/UserInfo/UserInfo.js
>            className={classes.menu}
could you please add an `id` here?

2021-10-21 08:01 UTC, jreynard-code commented on src/menus/UserInfo/UserInfo.js
> +            id="simple-menu"
Could you please change the `id` value? it'd be better named 'languages-menu

2021-10-26 12:56 UTC, merged