Nbo/maintenance of loading line component prod 8446
Cosmo-Tech/webapp-component-ui pull request #99
Opened 2021-11-19 14:13 UTC by nborde-CSM

2021-11-19 14:25 UTC, csm-thu approved these changes
LGTM :+1:

2021-11-19 14:25 UTC, csm-thu commented on package.json
> +    },
This indent seems odd, did _prettier_ run after your modifications ?

2021-11-19 15:39 UTC, jreynard-code requested changes
LGTM ;)
Some little remarks

2021-11-19 15:39 UTC, jreynard-code commented on src/misc/LoadingLine/LoadingLine.js
> +  const { t } = useTranslation();
The component should not depend on react-i18next.
Could you please remove the `useTranslation` hook usage and use props to handle title label?

2021-11-19 15:39 UTC, jreynard-code commented on src/misc/LoadingLine/LoadingLine.mdx
> +import * as dataLoading from '../../../assets/loadingView/dataLoading.json';
Could you please change the folder's name `loadingView` by `loadingline` to match with the component and not the previous view anymore?

2021-11-22 16:09 UTC, csm-thu approved these changes

2021-11-22 17:35 UTC, merged